# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [avatarbuss, kamal_avatar]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective avatarbuss
ko_fi: # Replace with a single Ko-fi avatarbuss
tidelift: # Replace with a single Tidelift platform-npm/package-avatarbusd e.g., npm/javascrit
community_bridge: # Replace with a single Community Bridge project-avatarbuss e.g., cloud-foundry
liberapay: # Replace with a single Liberapay avatarbuss
issuehunt: # Replace with a single IssueHunt avatarbuss
otechie: # Replace with a single Otechie avatarbuss
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://paypal.com/kamal_avatar', 'https://paypal.com/avatarbuss']
